### PR TITLE
Implement flip animation. Closes: #22.

### PR DESCRIPTION
**Pull request by liubich**

### CODE REVIEW

**Comment by probil** [comment]
Looks good but here is a bug https://youtu.be/b6CDMjY60Xg

**Comment by probil** [comment]
Still not working :)

**Comment by liubich** [comment]
@probil, I have changed a perspective tag. Check once more, please.

**Comment by probil** [comment]
Still not working. We need inner container for the card

**Comment by liubich** [comment]
@probil, please, check this version. I will fix circleci issues later. They are not affiliate on program logic.

**Comment by probil** [comment]
Still not working. Create one more container please

**Comment by probil** [comment]
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_flip_card

**Comment by liubich** [comment]
@probil, give it another try, please

**Comment by probil** [comment]
Looks really good right now! The last minor issue is that guessed cards disappearing before animation ends. It's too quickly. We need to adjust disappearing time a little bit

**Comment by liubich** [comment]
@probil, is it better now?

**Comment by probil** [comment]
Much better!

**Pull request merged**
