### PR TITLE
Add viewport meta. Closes: #4

### PR DESCRIPTION
**Pull request by liubich**

### CODE REVIEW

**Comment by probil** [comment]
Approved. Next time add me to the list of **Reviewers**

**Comment by liubich** [comment]
And now I should to merge this branch into master?

**Comment by liubich** [comment]
@probil, try to open a deploy-preview on mobile, please https://deploy-preview-11--serene-noyce-253ee0.netlify.com/
I see some disproportion((

**Comment by probil** [comment]
> And now I should to merge this branch into master?

Yes. There is a  **Merge** button at he bottom

**Comment by probil** [comment]
> @probil, try to open a deploy-preview on mobile, please https://deploy-preview-11--serene-noyce-253ee0.netlify.com/
> I see some disproportion((

There are a lot of issues on mobile. Viewport is only one step forward to make it work better. 
We will cover other issues later

**Pull request merged**
