### PR TITLE
Fix/7 js refactor

### PR DESCRIPTION
**Pull request by liubich**
I can't change this
`if(this.prevClicked === undefined)`
to this 
`if(!this.prevClicked)`
because `this.prevClicked` may be equal 0.

### CODE REVIEW

**Comment by probil** [comment]
You can because `0`, `undefined`, `null`, `''`, `NaN` are falsy values
```js
!0 // true
!undefined // true
!null // true
!'' // tru
```
This is how coercing work in JS

**Comment by probil** [comment]
Current git-tree:
Screen Shot 2019-03-15 at 17 02 01

Expected git-tree:
Screen Shot 2019-03-15 at 17 03 21

**Comment by liubich** [comment]
I forget to do `checkout master`.
!0 // true
0===undefined //false
Feel the difference))

**Comment by probil** [comment]
> because `this.prevClicked` may be equal 0.

Ok. I got it

**Pull request merged**
